package btth4gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * 
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHienThi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btSo7 = new javax.swing.JButton();
        btSo8 = new javax.swing.JButton();
        btSo9 = new javax.swing.JButton();
        btChia = new javax.swing.JButton();
        btSo4 = new javax.swing.JButton();
        btSo5 = new javax.swing.JButton();
        btSo6 = new javax.swing.JButton();
        btNhan = new javax.swing.JButton();
        btSo1 = new javax.swing.JButton();
        btSo2 = new javax.swing.JButton();
        btSo3 = new javax.swing.JButton();
        btTru = new javax.swing.JButton();
        btHuy = new javax.swing.JButton();
        btSo0 = new javax.swing.JButton();
        btBang = new javax.swing.JButton();
        btCong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbHienThi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbHienThi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbHienThi.setText("0");
        lbHienThi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel1.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        btSo7.setText("7");
        btSo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSo7ActionPerformed(evt);
            }
        });
        jPanel1.add(btSo7);

        btSo8.setText("8");
        btSo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSo8ActionPerformed(evt);
            }
        });
        jPanel1.add(btSo8);

        btSo9.setText("9");
        btSo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSo9ActionPerformed(evt);
            }
        });
        jPanel1.add(btSo9);

        btChia.setText("/");
        btChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChiaActionPerformed(evt);
            }
        });
        jPanel1.add(btChia);

        btSo4.setText("4");
        btSo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSo4ActionPerformed(evt);
            }
        });
        jPanel1.add(btSo4);

        btSo5.setText("5");
        btSo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSo5ActionPerformed(evt);
            }
        });
        jPanel1.add(btSo5);

        btSo6.setText("6");
        btSo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSo6ActionPerformed(evt);
            }
        });
        jPanel1.add(btSo6);

        btNhan.setText("X");
        btNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanActionPerformed(evt);
            }
        });
        jPanel1.add(btNhan);

        btSo1.setText("1");
        btSo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSo1ActionPerformed(evt);
            }
        });
        jPanel1.add(btSo1);

        btSo2.setText("2");
        btSo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSo2ActionPerformed(evt);
            }
        });
        jPanel1.add(btSo2);

        btSo3.setText("3");
        btSo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSo3ActionPerformed(evt);
            }
        });
        jPanel1.add(btSo3);

        btTru.setText("-");
        btTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTruActionPerformed(evt);
            }
        });
        jPanel1.add(btTru);

        btHuy.setText("C");
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });
        jPanel1.add(btHuy);

        btSo0.setText("0");
        btSo0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSo0ActionPerformed(evt);
            }
        });
        jPanel1.add(btSo0);

        btBang.setText("=");
        btBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBangActionPerformed(evt);
            }
        });
        jPanel1.add(btBang);

        btCong.setText("+");
        btCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCongActionPerformed(evt);
            }
        });
        jPanel1.add(btCong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSo0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSo0ActionPerformed
        // TODO add your handling code here:
        String gtri = this.lbHienThi.getText();
        if(gtri.length()<10){
            if(gtri.equals("0")) gtri="";
            this.lbHienThi.setText(gtri+btSo0.getText());
        }
    }//GEN-LAST:event_btSo0ActionPerformed

    private void btSo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSo1ActionPerformed
        // TODO add your handling code here:
        String gtri = this.lbHienThi.getText();
        if(gtri.length()<10){
            if(gtri.equals("0")) gtri="";
            this.lbHienThi.setText(gtri+btSo1.getText());
        }
    }//GEN-LAST:event_btSo1ActionPerformed

    private void btSo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSo2ActionPerformed
        // TODO add your handling code here:
        String gtri = this.lbHienThi.getText();
        if(gtri.length()<10){
            if(gtri.equals("0")) gtri="";
            this.lbHienThi.setText(gtri+btSo2.getText());
        }
    }//GEN-LAST:event_btSo2ActionPerformed

    private void btSo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSo3ActionPerformed
        // TODO add your handling code here:
        String gtri = this.lbHienThi.getText();
        if(gtri.length()<10){
            if(gtri.equals("0")) gtri="";
            this.lbHienThi.setText(gtri+btSo3.getText());
        }
    }//GEN-LAST:event_btSo3ActionPerformed

    private void btSo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSo4ActionPerformed
        // TODO add your handling code here:
        String gtri = this.lbHienThi.getText();
        if(gtri.length()<10){
            if(gtri.equals("0")) gtri="";
            this.lbHienThi.setText(gtri+btSo4.getText());
        }
    }//GEN-LAST:event_btSo4ActionPerformed

    private void btSo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSo5ActionPerformed
        // TODO add your handling code here:
        String gtri = this.lbHienThi.getText();
        if(gtri.length()<10){
            if(gtri.equals("0")) gtri="";
            this.lbHienThi.setText(gtri+btSo5.getText());
        }
    }//GEN-LAST:event_btSo5ActionPerformed

    private void btSo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSo6ActionPerformed
        // TODO add your handling code here:
        String gtri = this.lbHienThi.getText();
        if(gtri.length()<10){
            if(gtri.equals("0")) gtri="";
            this.lbHienThi.setText(gtri+btSo6.getText());
        }
    }//GEN-LAST:event_btSo6ActionPerformed

    private void btSo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSo7ActionPerformed
        // TODO add your handling code here:
        String gtri = this.lbHienThi.getText();
        if(gtri.length()<10){
            if(gtri.equals("0")) gtri="";
            this.lbHienThi.setText(gtri+btSo7.getText());
        }
    }//GEN-LAST:event_btSo7ActionPerformed

    private void btSo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSo8ActionPerformed
        // TODO add your handling code here:
        String gtri = this.lbHienThi.getText();
        if(gtri.length()<10){
            if(gtri.equals("0")) gtri="";
            this.lbHienThi.setText(gtri+btSo8.getText());
        }
    }//GEN-LAST:event_btSo8ActionPerformed

    private void btSo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSo9ActionPerformed
        // TODO add your handling code here:
        String gtri = this.lbHienThi.getText();
        if(gtri.length()<10){
            if(gtri.equals("0")) gtri="";
            this.lbHienThi.setText(gtri+btSo9.getText());
        }
    }//GEN-LAST:event_btSo9ActionPerformed
    private long kq=0;
    private String phepToan= "";
    private void tinh()
    {
        if(this.phepToan.equals("")) this.kq=Long.parseLong(lbHienThi.getText());
        else 
        {
            if(this.phepToan.equals("+")) this.kq +=Long.parseLong(lbHienThi.getText());
            if(this.phepToan.equals("-")) this.kq -=Long.parseLong(lbHienThi.getText());
            if(this.phepToan.equals("/")) this.kq /=Long.parseLong(lbHienThi.getText());
            if(this.phepToan.equals("X")) this.kq *=Long.parseLong(lbHienThi.getText());
        }
    }
    private void btCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCongActionPerformed
        // TODO add your handling code here:
        tinh();
        this.phepToan = "+";
        lbHienThi.setText("0");
    }//GEN-LAST:event_btCongActionPerformed

    private void btBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBangActionPerformed
        // TODO add your handling code here:
        tinh();
        lbHienThi.setText(String.valueOf(this.kq));
        this.kq=0;
    }//GEN-LAST:event_btBangActionPerformed

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        // TODO add your handling code here:
        lbHienThi.setText("0");
        this.phepToan="";
    }//GEN-LAST:event_btHuyActionPerformed

    private void btTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTruActionPerformed
        // TODO add your handling code here:
        tinh();
        this.phepToan = "-";
        lbHienThi.setText("0");
    }//GEN-LAST:event_btTruActionPerformed

    private void btNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanActionPerformed
        // TODO add your handling code here:
        tinh();
        this.phepToan = "X";
        lbHienThi.setText("0");
    }//GEN-LAST:event_btNhanActionPerformed

    private void btChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChiaActionPerformed
        // TODO add your handling code here:
        tinh();
        this.phepToan = "/";
        lbHienThi.setText("0");
    }//GEN-LAST:event_btChiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Calculator();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBang;
    private javax.swing.JButton btChia;
    private javax.swing.JButton btCong;
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btNhan;
    private javax.swing.JButton btSo0;
    private javax.swing.JButton btSo1;
    private javax.swing.JButton btSo2;
    private javax.swing.JButton btSo3;
    private javax.swing.JButton btSo4;
    private javax.swing.JButton btSo5;
    private javax.swing.JButton btSo6;
    private javax.swing.JButton btSo7;
    private javax.swing.JButton btSo8;
    private javax.swing.JButton btSo9;
    private javax.swing.JButton btTru;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbHienThi;
    // End of variables declaration//GEN-END:variables
}
